export const projects = [
  {
    title: 'E-commerse API',
    description: "Using Node.js, Express & MongoDB to create an impressive web API that allow admin to manage products, categories and control users.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'postman', 'Node'],
    source: 'https://github.com/vimolLay/API-Nodejs/tree/master',
    visit: 'https://github.com/vimolLay/API-Nodejs/tree/master',
    id: 0,
  },
  {
    title: 'Pizza/Drink E-shop Website',
    description:"Provided a dashboard that allows admin to add products Edit Delete and manage what customers buying...",
    image: '/images/2.png',
    tags: ['Laravel', 'Php blade','Mysql'],
    source: 'https://github.com/vimolLay/pizzabart/tree/master',
    visit: 'https://github.com/vimolLay/pizzabart/tree/master',
    id: 1,
  },
  {
    title: 'Shopify website',
    description: "We don't need to know much about code but we can used this platform to build our own e-shop website",
      image: '/images/3.png',
      tags: ['Shopify', 'HTML,CSS,Javascript','Liquid'],
    source: 'https://www.shopify.com/',
    visit: 'https://www.shopify.com/',
    id: 2,
  },
  {
    title: 'Blog Website',
    description: "KET is the blog website that provide books,articles,videos for Cambodian people to read and learn about History,People,Science,Health,Technology",
    image: '/images/4.png',
    tags: ['Vue js', 'Mongodb', 'Django','Docker'],
    source: 'http://178.128.212.4:8000/',
    visit: 'http://178.128.212.4:8000/',
    id: 3,
  },
  {
    title: 'Video/Digital Design',
    description: "Using Adobe Photoshop,Adobe Illustrator,Figma to design a very attractive posters and Adobe Premiere for the video",
    image: '/images/5.png',
    tags: ['Photoshop', 'AI', 'Figma','Adobe Premiere'],
    source: 'https://www.google.com/',
    visit: 'https://www.google.com/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];